# Generated by Django 4.0.3 on 2022-12-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.IntegerField(default=0),
        ),
    ]
